/**
 * Mock data for the Orios Portal homepage.
 * This file provides placeholder data for development.
 * Replace with real API calls when the backend is ready.
 *
 * All subject references use `subjectId` — a pointer to the
 * centralized subject registry in `lib/subjects.js`.
 */

export const mockStats = {
  classesToday: 4,
  pendingTasks: 3,
  upcomingEvents: 2,
  totalNotes: 24,
};

export const mockCountdowns = [
  {
    id: 1,
    title: "EEE 1201 Midterm",
    type: "exam",
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days from now
    subjectId: "eee-1201",
  },
  {
    id: 2,
    title: "PHY Lab Report 4",
    type: "lab",
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days from now
    subjectId: "phy-1201",
  },
  {
    id: 3,
    title: "MATH Assignment 3",
    type: "assignment",
    date: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(), // 8 days from now
    subjectId: "math-1201",
  },
];

export const mockSchedule = [
  {
    id: 1,
    time: "9:00",
    subjectId: "eee-1201",
    teacher: "Dr. Rahman",
    room: "Room 301",
    type: "lecture",
  },
  {
    id: 2,
    time: "10:00",
    subjectId: "phy-1201",
    teacher: "Prof. Ahmed",
    room: "Room 205",
    type: "lecture",
  },
  {
    id: 3,
    time: "11:30",
    subjectId: "cse-1201",
    teacher: "Ms. Fatima",
    room: "Lab 4",
    type: "lab",
  },
  {
    id: 4,
    time: "2:00",
    subjectId: "math-1201",
    teacher: "Dr. Khan",
    room: "Room 102",
    type: "lecture",
  },
];

export const mockFeatures = [
  {
    title: "Notes",
    description: "Subject-wise notes, links, docs, and resources.",
    href: "/notes",
    icon: "FileText",
  },
  {
    title: "Assignments",
    description: "Track assignments with due dates and status.",
    href: "/assignments",
    icon: "ClipboardList",
  },
  {
    title: "Lab Reports",
    description: "Manage lab reports organized by subject.",
    href: "/lab-reports",
    icon: "FlaskConical",
  },
  {
    title: "Calendar",
    description: "Events, routine, and important dates.",
    href: "/calendar",
    icon: "Calendar",
  },
  {
    title: "Teachers",
    description: "Contact info and details for all teachers.",
    href: "/teachers",
    icon: "GraduationCap",
  },
  {
    title: "File Sharing",
    description: "Share and download class materials.",
    href: "/files",
    icon: "FolderOpen",
  },
];

export const mockNotes = [
  {
    id: 1,
    title: "Circuit Analysis Basics",
    subjectId: "eee-1201",
    type: "pdf",
    date: "2025-06-20",
    description: "Introduction to Kirchhoff's laws and Ohm's law with examples.",
  },
  {
    id: 2,
    title: "AC vs DC Circuits",
    subjectId: "eee-1201",
    type: "pdf",
    date: "2025-06-18",
    description: "Comparison of AC and DC circuit behavior and applications.",
  },
  {
    id: 3,
    title: "Thevenin's Theorem Notes",
    subjectId: "eee-1201",
    type: "doc",
    date: "2025-06-15",
    description: "Step-by-step guide to solving circuits using Thevenin's theorem.",
  },
  {
    id: 4,
    title: "Newton's Laws of Motion",
    subjectId: "phy-1201",
    type: "pdf",
    date: "2025-06-22",
    description: "Detailed notes on all three laws with real-world examples.",
  },
  {
    id: 5,
    title: "Wave Optics Reference",
    subjectId: "phy-1201",
    type: "link",
    url: "https://example.com/wave-optics",
    date: "2025-06-19",
    description: "External resource covering diffraction and interference.",
  },
  {
    id: 6,
    title: "Rotational Mechanics Diagrams",
    subjectId: "phy-1201",
    type: "image",
    date: "2025-06-14",
    description: "Free body diagrams for torque and angular momentum problems.",
  },
  {
    id: 7,
    title: "Integration Techniques",
    subjectId: "math-1201",
    type: "pdf",
    date: "2025-06-21",
    description: "Covers substitution, by-parts, and partial fractions.",
  },
  {
    id: 8,
    title: "Differential Equations Cheat Sheet",
    subjectId: "math-1201",
    type: "doc",
    date: "2025-06-17",
    description: "Quick reference for solving first and second order ODEs.",
  },
  {
    id: 9,
    title: "Matrix Operations",
    subjectId: "math-1201",
    type: "pdf",
    date: "2025-06-12",
    description: "Determinants, inverses, eigenvalues, and eigenvectors.",
  },
  {
    id: 10,
    title: "Intro to C Programming",
    subjectId: "cse-1201",
    type: "pdf",
    date: "2025-06-23",
    description: "Variables, data types, control structures, and functions in C.",
  },
  {
    id: 11,
    title: "Data Structures Overview",
    subjectId: "cse-1201",
    type: "link",
    url: "https://example.com/dsa",
    date: "2025-06-16",
    description: "Arrays, linked lists, stacks, and queues explained.",
  },
  {
    id: 12,
    title: "Pointer Arithmetic Notes",
    subjectId: "cse-1201",
    type: "doc",
    date: "2025-06-10",
    description: "Understanding pointers, memory allocation, and arrays in C.",
  },
];

export const mockAssignments = [
  {
    id: 1,
    title: "Circuit Analysis Problem Set",
    subjectId: "eee-1201",
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: "pending",
    description: "Solve problems 3.1–3.15 from the textbook. Show all working.",
  },
  {
    id: 2,
    title: "MATH Assignment 3",
    subjectId: "math-1201",
    dueDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    status: "pending",
    description: "Integration and differential equations worksheet.",
  },
  {
    id: 3,
    title: "C Programming: Linked Lists",
    subjectId: "cse-1201",
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "pending",
    description: "Implement singly linked list with insert, delete, and search.",
  },
  {
    id: 4,
    title: "Physics Problem Set 2",
    subjectId: "phy-1201",
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: "submitted",
    description: "Rotational mechanics and angular momentum problems.",
  },
  {
    id: 5,
    title: "MATH Assignment 2",
    subjectId: "math-1201",
    dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "graded",
    grade: "A-",
    description: "Matrix operations and determinants.",
  },
  {
    id: 6,
    title: "Digital Logic Design HW 1",
    subjectId: "eee-1201",
    dueDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    status: "graded",
    grade: "B+",
    description: "Boolean algebra and Karnaugh maps.",
  },
];

export const mockLabReports = [
  {
    id: 1,
    title: "Ohm's Law Verification",
    subjectId: "eee-1201",
    labNumber: 1,
    dueDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    status: "submitted",
    description: "Verify Ohm's law using resistors and measure V-I characteristics.",
  },
  {
    id: 2,
    title: "KVL & KCL Experiment",
    subjectId: "eee-1201",
    labNumber: 2,
    dueDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: "submitted",
    description: "Verify Kirchhoff's voltage and current laws in a circuit.",
  },
  {
    id: 3,
    title: "Thevenin's Theorem",
    subjectId: "eee-1201",
    labNumber: 3,
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: "pending",
    description: "Find Thevenin equivalent circuit for a given network.",
  },
  {
    id: 4,
    title: "PHY Lab Report 4",
    subjectId: "phy-1201",
    labNumber: 4,
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: "pending",
    description: "Simple pendulum experiment — measure g and analyze errors.",
  },
  {
    id: 5,
    title: "Newton's 2nd Law",
    subjectId: "phy-1201",
    labNumber: 3,
    dueDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: "graded",
    grade: "A",
    description: "Verify F=ma using an Atwood machine setup.",
  },
  {
    id: 6,
    title: "Array Sorting Algorithms",
    subjectId: "cse-1201",
    labNumber: 5,
    dueDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    status: "pending",
    description: "Implement bubble sort, selection sort, and measure time complexity.",
  },
];

export const mockFiles = [
  {
    id: 1,
    name: "EEE_1201_Midterm_Syllabus.pdf",
    subjectId: "eee-1201",
    type: "pdf",
    size: "245 KB",
    uploadedBy: "Dr. Rahman",
    date: "2025-06-22",
  },
  {
    id: 2,
    name: "Circuit_Diagrams_Pack.zip",
    subjectId: "eee-1201",
    type: "zip",
    size: "12.4 MB",
    uploadedBy: "Rahat",
    date: "2025-06-20",
  },
  {
    id: 3,
    name: "PHY_Formula_Sheet.pdf",
    subjectId: "phy-1201",
    type: "pdf",
    size: "180 KB",
    uploadedBy: "Prof. Ahmed",
    date: "2025-06-21",
  },
  {
    id: 4,
    name: "Lecture_5_Slides.pptx",
    subjectId: "math-1201",
    type: "pptx",
    size: "3.2 MB",
    uploadedBy: "Dr. Khan",
    date: "2025-06-19",
  },
  {
    id: 5,
    name: "Lab5_Starter_Code.c",
    subjectId: "cse-1201",
    type: "code",
    size: "4 KB",
    uploadedBy: "Ms. Fatima",
    date: "2025-06-23",
  },
  {
    id: 6,
    name: "Assignment_3_Solutions.pdf",
    subjectId: "math-1201",
    type: "pdf",
    size: "520 KB",
    uploadedBy: "Tasnim",
    date: "2025-06-18",
  },
  {
    id: 7,
    name: "CSE_Midterm_Past_Papers.zip",
    subjectId: "cse-1201",
    type: "zip",
    size: "8.1 MB",
    uploadedBy: "Sakib",
    date: "2025-06-17",
  },
  {
    id: 8,
    name: "PHY_Lab_Manual.pdf",
    subjectId: "phy-1201",
    type: "pdf",
    size: "1.8 MB",
    uploadedBy: "Prof. Ahmed",
    date: "2025-06-15",
  },
];

export const mockTeachers = [
  {
    id: 1,
    name: "Dr. Abdur Rahman",
    subjectIds: ["eee-1201"],
    role: "Professor",
    email: "a.rahman@univ.edu",
    phone: "+880-1711-XXXXXX",
    room: "Room 301, EEE Building",
    officeHours: "Sun & Tue 10:00 – 12:00",
    initials: "AR",
  },
  {
    id: 2,
    name: "Prof. Kamal Ahmed",
    subjectIds: ["phy-1201"],
    role: "Associate Professor",
    email: "k.ahmed@univ.edu",
    phone: "+880-1812-XXXXXX",
    room: "Room 205, Science Building",
    officeHours: "Mon & Wed 11:00 – 1:00",
    initials: "KA",
  },
  {
    id: 3,
    name: "Ms. Fatima Akter",
    subjectIds: ["cse-1201"],
    role: "Lecturer",
    email: "f.akter@univ.edu",
    phone: "+880-1913-XXXXXX",
    room: "Lab 4, CSE Building",
    officeHours: "Tue & Thu 2:00 – 4:00",
    initials: "FA",
  },
  {
    id: 4,
    name: "Dr. Imran Khan",
    subjectIds: ["math-1201"],
    role: "Professor",
    email: "i.khan@univ.edu",
    phone: "+880-1614-XXXXXX",
    room: "Room 102, Math Building",
    officeHours: "Sun & Wed 9:00 – 11:00",
    initials: "IK",
  },
];
